'use client';

/**
 * Privacy Policy — public legal page.
 * Linked from footer; previously 404'd. SwisDex-specific copy adapted from
 * a standard GDPR/UK-DPA compliant template.
 */
import Link from 'next/link';
import { Lock, ArrowUpRight, ShieldCheck, Mail } from 'lucide-react';
import { BannerPlaceholder } from '@/swisdex/components/BannerPlaceholder';

const SECTIONS = [
  {
    h: '1. Who We Are',
    p: `SwisDex (the "Company", "we", "us") is the data controller responsible for the personal data
    you submit through swisdex.com, the SwisDex web platform, and our mobile applications. Our
    registered office is Office 23US, 18 Young St, UNIT LGE 1/1, Edinburgh EH2 4JB, Scotland,
    United Kingdom.`,
  },
  {
    h: '2. What Data We Collect',
    p: `We collect data you provide directly (name, email, phone, date of birth, government-issued
    ID for KYC, proof of address, trading preferences), data generated by your activity (orders,
    trades, P&L, login events, IP address, device, browser, geo-location, support chats), and
    cookies / similar tracking technologies described in the Cookies section below.`,
  },
  {
    h: '3. Why We Collect It',
    p: `We process your data to: (a) open and operate your trading account; (b) comply with our
    legal obligations (KYC/AML, tax reporting, regulatory disclosure); (c) execute and settle
    trades; (d) prevent fraud, money laundering, and platform abuse; (e) provide customer support;
    (f) improve the platform; and (g) where permitted, send you product and marketing updates you
    can unsubscribe from at any time.`,
  },
  {
    h: '4. Lawful Bases',
    p: `Depending on the activity, we rely on: contract (operating your account), legal obligation
    (regulatory compliance), legitimate interests (fraud prevention, platform improvement), and
    consent (marketing). Where we rely on consent you may withdraw it at any time by emailing
    privacy@swisdex.com.`,
  },
  {
    h: '5. Who We Share With',
    p: `Trusted third parties acting on our instructions: KYC and identity-verification providers,
    cloud and analytics infrastructure, payment processors, banking partners, anti-fraud vendors,
    and our regulators where required by law. We do NOT sell your personal data to advertisers.`,
  },
  {
    h: '6. International Transfers',
    p: `Some of our processors are located outside your country of residence. Where we transfer your
    data outside the UK / EEA we rely on Standard Contractual Clauses or another approved
    safeguard so your data continues to enjoy comparable protection.`,
  },
  {
    h: '7. How Long We Keep It',
    p: `Account, KYC, and trading records are retained for the period required by financial
    regulation (typically 5–7 years after account closure). Marketing data is retained until you
    unsubscribe or after 24 months of inactivity, whichever is shorter.`,
  },
  {
    h: '8. Your Rights',
    p: `Subject to local law you may request access, rectification, erasure, restriction, or
    portability of your personal data, and object to certain processing. You also have the right
    to lodge a complaint with your supervisory authority. To exercise these rights, email
    privacy@swisdex.com — we will respond within 30 days.`,
  },
  {
    h: '9. Cookies & Similar Technologies',
    p: `We use strictly-necessary cookies to operate the platform (authentication, security,
    preferences) and, with your consent, performance / analytics cookies to understand usage. You
    can manage cookies via your browser settings or the in-app preferences screen. Disabling
    strictly-necessary cookies may break key features.`,
  },
  {
    h: '10. Security',
    p: `We protect your data with industry-standard controls: TLS in transit, AES-256 at rest,
    role-based access controls, segregated production environments, and continuous security
    monitoring. No system is ever 100% secure — notify us immediately at security@swisdex.com if
    you suspect a breach of your account.`,
  },
  {
    h: '11. Children',
    p: `Our Services are not directed at children under 18. We do not knowingly collect personal
    data from minors. If you believe a minor has registered, contact privacy@swisdex.com and we
    will delete the account.`,
  },
  {
    h: '12. Changes',
    p: `We may update this Policy from time to time. Material changes will be notified by email
    and/or an in-app banner. The latest version is always published at swisdex.com/privacy.`,
  },
  {
    h: '13. Contact',
    p: `Questions about this Policy or your data? Email privacy@swisdex.com or write to the
    registered office listed above. For general queries see /company/contact.`,
  },
];

export default function PrivacyPage() {
  return (
    <main className="min-h-screen bg-background">
      <BannerPlaceholder
        title="Privacy Policy"
        tagline="What personal data we collect, why we collect it, and how we keep it safe."
      />

      <section className="mx-auto max-w-[840px] px-[var(--gutter)] pt-10 pb-6">
        <div className="liquid-glass rounded-2xl px-5 py-4 flex items-center gap-3 text-sm text-foreground/70">
          <Lock className="size-4 text-primary shrink-0" />
          <span>
            <span className="font-semibold text-foreground/90">Effective date:</span> January 1, 2026 ·
            Last updated: June 2026
          </span>
        </div>
      </section>

      <article className="mx-auto max-w-[840px] px-[var(--gutter)] py-8 sm:py-10 space-y-7">
        {SECTIONS.map(({ h, p }) => (
          <section key={h} className="liquid-glass rounded-2xl p-6 sm:p-7">
            <h2 className="font-display text-lg sm:text-xl uppercase tracking-tight text-foreground mb-3">
              {h}
            </h2>
            <p className="text-sm sm:text-[15px] leading-relaxed text-foreground/75">{p}</p>
          </section>
        ))}

        <div className="liquid-glass-strong rounded-2xl p-6 sm:p-7 flex flex-col sm:flex-row gap-4 sm:items-center sm:justify-between">
          <div className="flex items-start gap-3">
            <ShieldCheck className="size-5 text-primary shrink-0 mt-0.5" />
            <p className="text-sm text-foreground/75 leading-relaxed">
              Read this alongside our{' '}
              <Link href="/terms" className="text-primary underline-offset-4 hover:underline">
                Terms of Service
              </Link>{' '}
              and{' '}
              <Link href="/risk" className="text-primary underline-offset-4 hover:underline">
                Risk Disclaimer
              </Link>
              .
            </p>
          </div>
          <a
            href="mailto:privacy@swisdex.com"
            className="inline-flex items-center gap-2 rounded-full bg-primary text-white px-5 py-2.5 text-sm font-semibold uppercase tracking-wider hover:opacity-90 shrink-0"
          >
            <Mail className="size-4" /> Privacy Team
          </a>
        </div>
      </article>

      <section className="mx-auto max-w-[1200px] px-[var(--gutter)] pb-20">
        <div className="liquid-glass-strong rounded-3xl p-8 sm:p-12 text-center">
          <h2 className="font-display uppercase text-2xl sm:text-3xl tracking-tight">
            Your Data, Your Control
          </h2>
          <p className="mt-4 text-foreground/70 max-w-xl mx-auto text-sm sm:text-base">
            Open a SwisDex account confident that we treat your personal data with the same care we
            apply to your trading capital.
          </p>
          <Link
            href="/auth/register"
            className="mt-7 inline-flex items-center gap-2 rounded-full bg-primary text-white px-6 py-3 text-sm font-semibold uppercase tracking-wider hover:opacity-90"
          >
            Open Account <ArrowUpRight className="size-4" />
          </Link>
        </div>
      </section>
    </main>
  );
}
